on:
  push:
    branches:
      - master
jobs:
  generate-docs:
    runs-on: windows-latest
    name: Generate Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core 2.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.0"
      - name: Generate Documentation
        uses: FuLagann/csharp-docs-generator@v1.0
        with:
          build-tasks: dotnet build
          cleanup-tasks: dotnet clean
          binaries: src/Dummy.Library/bin/Debug/netstandard2.0/Dummy.Library.dll
          output-path: docs/
          user-email: csharp.doc.gen@gmail.com
          user-name: C# Document Generator
